-- ============================================================
-- RLS TO'LIQ O'CHIRISH - BU SKRIPTNI SQL EDITOR'DA ISHLA
-- ============================================================

-- BARCHA JADVALLAR UCHUN RLS O'CHIRISH
ALTER TABLE IF EXISTS public.clinics DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.patients DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.appointments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.services DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.service_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.treatment_plans DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tooth_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.implants DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.recalls DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.debts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.xrays DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.technicians DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.technician_jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cases DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.case_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.advertisements DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.botconfigs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.telegrambookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.scheduled_notifications DISABLE ROW LEVEL SECURITY;

-- GRANT BERISH
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated;

-- KELAJAKDAGI JADVALLAR UCHUN HAM
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated;

-- TEKSHIRISH - MANA SHU RAQAMLAR CHIQISHI KERAK
SELECT schemaname, tablename, rowsecurity 
FROM pg_tables 
WHERE schemaname = 'public'
ORDER BY tablename;

SELECT 'SUCCESS: RLS disabled and GRANT applied!' as result;
